### ISSUE TITLE
Plugin works only with Gradle 5.x

### ISSUE THREAD

**Issue by plnice** [plnice/can-i-drop-jetifier#1]

**Comment by pocmo** [comment]
I see the following exception with Gradle 4.10.1:

```
java.lang.NoSuchFieldError: Companion
        at com.github.plnice.canidropjetifier.CanIDropJetifierPlugin.apply(CanIDropJetifierPlugin.kt:26)
        at com.github.plnice.canidropjetifier.CanIDropJetifierPlugin.apply(CanIDropJetifierPlugin.kt:12)
       [..]
```

Is this what this issue is about?

**Comment by plnice** [comment]
@pocmo yes, that's the issue. After upgrading to Gradle 5.x the exception should be gone. Unfortunately, right now I can't see the way of fixing the issue without rewriting the plugin in Groovy...

**Comment by moisesvs** [comment]
I need that the plugin works with 4.10.1. 

Could you update the repository?

**Comment by vanniktech** [comment]
Just use Gradle 5.0

**Comment by plnice** [comment]
@moisesvs unfortunately, as I stated in the previous comment, I cannot make the plugin work with Gradle 4.x without a major rewrite that would decrease the quality of the code. As far as I know, the migration process from Gradle 4.x to 5.x shouldn't be painful for most of the cases, and the Gradle 5.x branch contains various improvements, so I consider migration to Gradle 5.x as a preferred solution to this issue.

**Comment by svenjacobs** [comment]
I think the recommended Gradle version for Android Studio / Android Gradle Plugin 3.3 is **4.10** at the moment so _imho_ the plugin should be working with Gradle 4.10 ;) I tried Gradle 5 but had to revert to 4.10 because my Android environment was not working well with Gradle 5.

**Comment by kahakai** [comment]
You can now safely use this plugin as AS 3.4 stable is out and it requires minimum Gradle version 5.1.1.

**Comment by plnice** [comment]
Since 5.x is now required by AGP, I close this issue.
