### ISSUE TITLE
Received status code 521

### ISSUE THREAD

**Issue by ppamorim** [plnice/can-i-drop-jetifier#10]
Hi, I am getting this error on my AS:

```
Could not GET 'https://jitpack.io/com/github/plnice/canidropjetifier/0.4/canidropjetifier-0.4.pom'. Received status code 521 from server: Origin Down
Enable Gradle 'offline mode' and sync project
```

Any idea how to solve this?

**Comment by plnice** [comment]
Hi, the plugin is hosted on the Gradle plugin portal, so please make sure you have `gradlePluginPortal()` **before** jitpack on your repositories list (in the `buildscript` block). The second option is to match the plugin to the repository (as explained [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies)):
```
buildscript {
  repositories {
    gradlePluginPortal() {
      content { 
        includeGroup "com.github.plnice"  
      }
    }
  }
}
```
Let me know if any of the options works for you!

**Comment by ppamorim** [comment]
@plnice Thank you.
It's working now, I think jitpack was out.
