### ISSUE TITLE
Requires kotlin gradle plugin for android

### ISSUE THREAD

**Issue by stephanenicolas** [plnice/can-i-drop-jetifier#2]
It looks like this plugin can only be applied to modules using kotlin for android. Right ?
Maybe you could add it to the docs (same as for gradle 5 being required).

**Comment by plnice** [comment]
Though the plugin is written 100% in Kotlin, you can apply it to projects which are not using Kotlin, and to projects that don't utilize Gradle Kotlin DSL. I've checked only small, sample Java-based application, but there should be no issues also with bigger projects. The only limitation is using Gradle 5.0+. Please let me know if you run into any issue related to Kotlin.

**Comment by stephanenicolas** [comment]
All is working fine now. I probably had a wrong setup.
