### ISSUE TITLE
Where to use the plugin in a modularized app ?

### ISSUE THREAD

**Issue by stephanenicolas** [plnice/can-i-drop-jetifier#3]
Can the plugin be used only in application modules or should it be applied to all libraries modules as well ?

**Comment by plnice** [comment]
The plugin is designed to be applied in the top-level `build.gradle` file. The single task created in the project root operates on all modules that are available in the project. Please let me know if this answers your question.

**Comment by stephanenicolas** [comment]
I had tried the plugin only on our application module. All is working fine when applied to the main `build.gradle` file.
