### ISSUE TITLE
More detailed error message if a module can't be AndroidX only

### ISSUE THREAD

**Issue by vanniktech** [plnice/can-i-drop-jetifier#7]
```
Cannot drop Jetifier due to following dependencies:

* vanniktech:testing-android:unspecified

* vanniktech:analytics-fcm:unspecified
```

`testing-android` and `analytics-fcm` are modules within my repository and they have dependencies which aren't on AndroidX. Would be helpful to get these directly when running the task on app level.

**Comment by plnice** [comment]
Thanks, good idea! Will implement the change in the coming days.

**Comment by plnice** [comment]
In 0.5 I've changed the way of reporting module dependencies that use obsolete artifacts, please let me know if this works for you :-)

**Comment by vanniktech** [comment]
Feel free to close. I've been mostly being able to drop jetifier in my projects for now.
