### ISSUE TITLE
Playservices & Firebase libraries

### ISSUE THREAD

**Issue by markchristopherng** [plnice/can-i-drop-jetifier#9]
Hi,

Thanks for the plugin, question around the results. I am using the latest libraries for Playservices & Firebase and the plugin reports that they need to be jetified. I couldn't find any Android X versions of them, is this correct?

Cannot drop Jetifier due to following dependencies:

* com.google.android.gms:play-services-auth:16.0.1

* com.google.android.gms:play-services-maps:16.1.0

* com.google.android.gms:play-services-location:16.0.0

* com.google.android.gms:play-services-awareness:16.0.0

* com.google.android.gms:play-services-auth-api-phone:16.0.0

* com.google.firebase:firebase-messaging:17.4.0

* com.google.firebase:firebase-ml-vision:19.0.2

* com.google.firebase:firebase-core:16.0.7

* com.google.firebase:firebase-messaging:17.4.0

* com.google.android.support:wearable:2.4.0

* com.google.android.gms:play-services-wearable:16.0.1

**Comment by plnice** [comment]
Yes, unfortunately Google didn't provide the AndroidX-based versions of those packages yet, so you cannot drop Jetifier until they are released and you use them.

**Comment by ppamorim** [comment]
@plnice That's really confusing since it's a collection of libraries provided by them...

**Comment by aried3r** [comment]
The June update of most of these libraries have migrated to AndroidX. See https://firebase.google.com/support/release-notes/android#update_-_june_17_2019 and https://developers.google.com/android/guides/releases#june_17_2019

**Comment by markchristopherng** [comment]
Great thanks for the update!
